### ISSUE TITLE
how to solve the equation of the line "Ax + By + C = 0" in this library

### ISSUE THREAD

**Issue by insinfo** [src-mgra/solvegls#1]
how to solve the equation of the line "y = (-C - Ax) / B" in this library

```dart
var A = 1.3333333333333333;
var B = -1;
var C = 0.3333333333333335;

//y = (-C - Ax) / B
//Y = (-0.3333333333333335 - 1.3333333333333333 * X) / -1

```

**Comment by src-mgra** [comment]
Hi, the library implements the gauss algorithm.
You need to have for each variable a equation with sorted factors as you can see in the example:
(only square matrix)

   1x+1y+1z=3
     2x-3y-1z=2
     4x-5y-1z=1
 
factor-array:    
 [1,1,1,3],
[2,-3,-1,2],
[4,-5,-1,1]

Put matrix size and factor-array to request:
var eq = require('jsequation-solver/eq-calc');
result = eq.eqcalc('{"size":3,"matrix":[[1,1,1,3],[2,-3,-1,2],[4,-5,-1,1]]}');
console.log(result);

The library puts the factors in the gauss algorithm and solves the resulting staggered matrix, it don't solves the equation it self.
I hope this helps.

**Comment by src-mgra** [comment]
Works with matrix as describe above!
